backend:
  name: github
  repo: kaamoskuoro/kaamos-website
  branch: main
media_folder: static/assets
site_url: https://kaamos.netlify.com
editor:
  preview: false
collections:
  - name: pages
    label: Pages
    label_singular: Page
    sortable_fields: []
    files:
      - name: sidebar
        label: Sidebar
        file: content/sidebar.yml
        fields:
          - name: newsItems
            label: News Items
            label_singular: News Item
            widget: list
            summary: "{{title}}"
            fields:
              - { name: title, label: Title, widget: string }
              - { name: body, label: Body, widget: text }
          - name: contactPersons
            label: Contact Persons
            label_singular: Contact Person
            widget: list
            summary: "{{name}}"
            fields:
              - { name: name, label: Name, widget: string }
              - { name: email, label: Email, widget: string }
              - { name: phone, label: Phone, widget: string }
      - name: home
        label: Home
        file: content/home.yml
        fields:
          - name: quotes
            label: Quotes
            label_singular: Quote
            widget: list
            summary: "{{body}} ({{author}}, {{publication}})"
            fields:
              - { name: body, label: Body, widget: text, default: "””" }
              - { name: author, label: Author, widget: string }
              - { name: publication, label: Publication, widget: string }
      - name: choir
        label: Choir
        file: content/choir.yml
        fields:
          - name: sopranos
            label: Sopranos
            label_singular: Soprano
            widget: list
            summary: "{{name}}"
            minimize_collapsed: true
            field: { name: name, label: Name, widget: string }
          - name: altos
            label: Altos
            label_singular: Alto
            widget: list
            summary: "{{name}}"
            minimize_collapsed: true
            field: { name: name, label: Name, widget: string }
          - name: tenors
            label: Tenors
            label_singular: Tenor
            widget: list
            summary: "{{name}}"
            minimize_collapsed: true
            field: { name: name, label: Name, widget: string }
          - name: basses
            label: Basses
            label_singular: Bass
            widget: list
            summary: "{{name}}"
            minimize_collapsed: true
            field: { name: name, label: Name, widget: string }
      - name: concerts
        label: Concerts
        file: content/concerts.yml
        fields:
          - name: concerts
            label: Concerts
            label_singular: Concert
            widget: list
            summary: "{{title}}"
            minimize_collapsed: true
            fields:
              - { name: title, label: Title, widget: string }
              - {
                  name: begins,
                  label: Begins,
                  widget: datetime,
                  default: "",
                  format: "YYYY-MM-DD HH:mm",
                  date_format: "D MMMM YYYY",
                  time_format: "HH:mm",
                }
              - { name: venue, label: Venue, widget: string }
              - { name: address, label: Address, widget: string }
              - {
                  name: description,
                  label: Description,
                  widget: text,
                  required: false,
                }
              - {
                  name: conductor,
                  label: Conductor,
                  widget: string,
                  required: false,
                }
              - {
                  name: admission,
                  label: Admission,
                  widget: string,
                  required: false,
                }
              - {
                  name: ticketURL,
                  label: Ticket URL,
                  widget: string,
                  required: false,
                }
