backend:
  name: github
  repo: kaamoskuoro/kaamos-website
  branch: main
media_folder: static/assets
collections:
  - name: pages
    label: Pages
    label_singular: Page
    files:
      - name: sidebar
        label: Sidebar
        file: content/sidebar.yml
        fields:
          - name: newsItems
            label: News Items
            label_singular: News Item
            widget: list
            summary: "{{title}}"
            fields:
              - { name: title, label: Title, widget: string }
              - { name: body, label: Body, widget: string }
          - name: contactPersons
            label: Contact Persons
            label_singular: Contact Person
            widget: list
            summary: "{{name}}"
            fields:
              - { name: name, label: Name, widget: string }
              - { name: email, label: Email, widget: string }
              - { name: phone, label: Phone, widget: string }
      - name: home
        label: Home
        file: content/home.yml
        fields:
          - name: quotes
            label: Quotes
            label_singular: Quote
            widget: list
            summary: "{{author}}, {{publication}}"
            fields:
              - { name: body, label: Body, widget: string, default: "””" }
              - { name: author, label: Author, widget: string }
              - { name: publication, label: Publication, widget: string }
      - name: singers
        label: Singers
        file: content/singers.yml
        fields:
          - name: sopranos
            label: Sopranos
            label_singular: Soprano
            widget: list
            summary: "{{name}}"
            minimize_collapsed: true
            field: { name: name, label: Name, widget: string }
          - name: altos
            label: Altos
            label_singular: Alto
            widget: list
            summary: "{{name}}"
            minimize_collapsed: true
            field: { name: name, label: Name, widget: string }
          - name: tenors
            label: Tenors
            label_singular: Tenor
            widget: list
            summary: "{{name}}"
            minimize_collapsed: true
            field: { name: name, label: Name, widget: string }
          - name: basses
            label: Basses
            label_singular: Bass
            widget: list
            summary: "{{name}}"
            minimize_collapsed: true
            field: { name: name, label: Name, widget: string }
